package steward

// Icon resolution.
//
// Every Lucide icon is available, from one vendored sprite (assets/dist/
// lucide-sprite.svg, ~400 KB for ~1,600 symbols) rather than a file per icon.
// The sprite is parsed once at boot into name → inner markup, so {{icon}} keeps
// inlining a complete <svg> — no per-page weight, no external reference, nothing
// for a strict CSP to object to. The same file is served to the browser for the
// icon picker's grid, where <use> against one cached sprite beats inlining
// sixteen hundred glyphs into the page.
//
// Resolution order for a name:
//
//  1. icons/<name>.svg through the asset layers — an app's own overlay wins, so
//     a project can override a Lucide glyph or add one of its own.
//  2. the sprite, after applying legacyIconAliases.
//  3. nothing, which renders an empty span; Verify reports it.

import (
	"io/fs"
	"sort"
	"strings"
)

// legacyIconAliases maps names Steward shipped before the sprite onto their
// current Lucide equivalents. Lucide has renamed these upstream; keeping the old
// names working means an existing panel's sidebar does not go blank on upgrade.
//
// Aliases resolve but are not offered in the picker, so new code reaches for the
// canonical name.
var legacyIconAliases = map[string]string{
	"home":        "house",
	"news":        "newspaper",
	"filter":      "funnel",
	"menu-2":      "menu",
	"columns":     "columns-3",
	"circle-help": "circle-question-mark",
	"info-circle": "info",
}

// iconSet is the parsed sprite: each symbol's inner markup, plus the sorted
// names for the picker.
type iconSet struct {
	symbols map[string]string
	names   []string
}

// spriteAttrs are the root-element attributes Lucide's individual files carry.
// The sprite's symbols hold only shape elements, so rendering one means
// supplying these — otherwise the glyph has no coordinate system and no stroke.
const spriteAttrs = `xmlns="http://www.w3.org/2000/svg" width="24" height="24" ` +
	`viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ` +
	`stroke-linecap="round" stroke-linejoin="round"`

// parseSprite extracts every <symbol id="…">…</symbol> body.
//
// Scanned rather than XML-decoded on purpose: the file is generated by
// lucide-static with one flat level of symbols and no namespacing, and keeping
// the inner markup verbatim is simpler than round-tripping it through a decoder.
func parseSprite(raw []byte) *iconSet {
	set := &iconSet{symbols: map[string]string{}}
	s := string(raw)
	const openTag = `<symbol id="`
	for i := 0; ; {
		start := strings.Index(s[i:], openTag)
		if start < 0 {
			break
		}
		start += i + len(openTag)
		end := strings.IndexByte(s[start:], '"')
		if end < 0 {
			break
		}
		name := s[start : start+end]

		bodyStart := strings.IndexByte(s[start+end:], '>')
		if bodyStart < 0 {
			break
		}
		bodyStart += start + end + 1
		bodyEnd := strings.Index(s[bodyStart:], "</symbol>")
		if bodyEnd < 0 {
			break
		}
		if name != "" {
			set.symbols[name] = strings.TrimSpace(s[bodyStart : bodyStart+bodyEnd])
		}
		i = bodyStart + bodyEnd
	}
	set.names = make([]string, 0, len(set.symbols))
	for n := range set.symbols {
		set.names = append(set.names, n)
	}
	sort.Strings(set.names)
	return set
}

// resolve returns a name's inner markup, following an alias when needed.
func (s *iconSet) resolve(name string) (string, bool) {
	if s == nil {
		return "", false
	}
	if body, ok := s.symbols[name]; ok {
		return body, true
	}
	if canonical, ok := legacyIconAliases[name]; ok {
		body, ok := s.symbols[canonical]
		return body, ok
	}
	return "", false
}

// wrap builds the complete <svg> for a symbol body.
func wrapSymbol(name, body, classes string) string {
	cls := "lucide lucide-" + name
	if classes != "" {
		cls = classes + " " + cls
	}
	return `<svg class="` + cls + `" ` + spriteAttrs + `>` + body + `</svg>`
}

// overlayIconNames lists icons present as files in the asset layers — an app's
// own additions, and any glyph it overrides.
func overlayIconNames(layers []fs.FS) []string {
	seen := map[string]bool{}
	for _, l := range layers {
		entries, err := fs.ReadDir(l, "icons")
		if err != nil {
			continue
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".svg") {
				continue
			}
			seen[strings.TrimSuffix(e.Name(), ".svg")] = true
		}
	}
	names := make([]string, 0, len(seen))
	for n := range seen {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// iconNames lists every pickable icon: the sprite's canonical names plus any
// overlay files. Legacy aliases are deliberately absent — they resolve, but
// offering them alongside their canonical twin only invites confusion about
// which one to use.
func (r *renderer) iconNames() []string {
	seen := map[string]bool{}
	if r.iconSet != nil {
		for _, n := range r.iconSet.names {
			seen[n] = true
		}
	}
	for _, n := range overlayIconNames(r.assetLayers) {
		seen[n] = true
	}
	names := make([]string, 0, len(seen))
	for n := range seen {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// Icons lists the icon names available to this panel, sorted — for a form field
// or a custom page that lets someone choose one.
func (a *Admin) Icons() []string {
	if a.renderer == nil {
		return nil
	}
	return a.renderer.iconNames()
}

// spritePath is where vendor-lucide stages the sprite, inside the asset layers.
const spritePath = "dist/lucide-sprite.svg"

// loadIconSet reads and parses the vendored sprite. A missing sprite is not an
// error: overlay icons still resolve, and the picker simply has less to offer.
func loadIconSet(layers []fs.FS) *iconSet {
	raw, err := readLayered(layers, spritePath)
	if err != nil {
		return &iconSet{symbols: map[string]string{}}
	}
	return parseSprite(raw)
}
