// Command assets builds Steward's frontend bundle without Node: JavaScript
// through the esbuild Go API, CSS through the Tailwind standalone binary
// (a native executable — see `make tailwind-bin`). Output lands in
// assets/dist and ships inside the Go binary via go:embed.
//
//	go run ./tools/assets           # one-shot production build
//	go run ./tools/assets -watch    # rebuild on change (dev)
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"

	"github.com/evanw/esbuild/pkg/api"
)

func main() {
	watch := flag.Bool("watch", false, "rebuild on change")
	flag.Parse()

	root, err := repoRoot()
	if err != nil {
		fatal(err)
	}

	js := api.BuildOptions{
		EntryPoints:       []string{filepath.Join(root, "frontend/src/app.js")},
		Outfile:           filepath.Join(root, "assets/dist/app.js"),
		Bundle:            true,
		Write:             true,
		MinifyWhitespace:  !*watch,
		MinifyIdentifiers: !*watch,
		MinifySyntax:      !*watch,
		Target:            api.ES2020,
		LogLevel:          api.LogLevelInfo,
		// htmx uses direct eval on purpose (hx-on:, event filters, js:
		// prefixes); esbuild already disables identifier renaming in that
		// one scope, so its warning is noise for a vendored file we won't
		// change. Anything louder than a warning still gets through.
		LogOverride: map[string]api.LogLevel{"direct-eval": api.LogLevelSilent},
	}

	if !*watch {
		if result := api.Build(js); len(result.Errors) > 0 {
			os.Exit(1)
		}
		if err := buildCSS(root); err != nil {
			fatal(err)
		}
		fmt.Printf("assets built into assets/dist (%d style packs)\n", len(styles))
		return
	}

	// Watch mode follows the shared bundle and the default pack only: one
	// Tailwind process per bundle, and nine of them would compile the same
	// sources on every keystroke. Run the one-shot build before checking
	// another pack.
	entry, err := entryFor(root, defaultStyle)
	if err != nil {
		fatal(err)
	}
	tw := tailwindCmd(root, filepath.Join(root, "frontend/src/app.css"),
		filepath.Join(root, "assets/dist/app.css"), true)
	twStyle := tailwindCmd(root, entry,
		filepath.Join(root, "assets/dist/style-"+defaultStyle+".css"), true)

	// *api.ContextError, not error: assigning it to an error variable would
	// wrap a nil pointer in a non-nil interface, and the check below would
	// always fire.
	ctx, ctxErr := api.Context(js)
	if ctxErr != nil {
		fatal(ctxErr)
	}
	if err := ctx.Watch(api.WatchOptions{}); err != nil {
		fatal(err)
	}
	tw.Stdout, tw.Stderr = os.Stdout, os.Stderr
	twStyle.Stdout, twStyle.Stderr = os.Stdout, os.Stderr
	if err := tw.Start(); err != nil {
		fatal(fmt.Errorf("tailwind: %w (run `make tailwind-bin`)", err))
	}
	if err := twStyle.Start(); err != nil {
		fatal(fmt.Errorf("tailwind (%s): %w", defaultStyle, err))
	}
	fmt.Printf("watching frontend/ — shared bundle and %s — Ctrl-C to stop\n", defaultStyle)

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt)
	<-sig
	ctx.Dispose()
	_ = tw.Process.Kill()
	_ = twStyle.Process.Kill()
	_ = os.Remove(entry)
}

// styles are Basecoat's style packs, and must match steward.Styles(). The two
// lists cannot be shared: this is a separate module, so it cannot import the
// library. A test in the library asserts a bundle exists for every Style,
// which is what catches a pack added on one side only.
var styles = []string{"vega", "nova", "maia", "lyra", "mira", "luma", "sera", "rhea"}

// defaultStyle is the one watch mode builds. It must match steward.DefaultStyle.
const defaultStyle = "vega"

// entryFor writes the Tailwind entry for one pack and returns its path.
//
// The file lives beside app.css because both @reference and the pack import
// are resolved relative to it, and app.css's own @source globs are relative to
// its directory. It is generated rather than committed so that a change to the
// composition is made in one place.
func entryFor(root, style string) (string, error) {
	path := filepath.Join(root, "frontend/src", ".style-"+style+".css")
	body := "/* Generated by tools/assets. Edit entryFor, not this file. */\n" +
		// @reference loads app.css for context — tokens, @theme, @custom-variant —
		// without emitting it again, so the bundle holds the pack's component
		// layer and nothing else.
		"@reference \"./app.css\";\n" +
		"@import \"../vendor/basecoat/styles/" + style + ".css\";\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("writing entry for %s: %w", style, err)
	}
	return path, nil
}

// tailwindBin finds the standalone binary: frontend/.bin/tailwindcss
// (installed by `make tailwind-bin`), then $PATH.
func tailwindBin(root string) string {
	bin := filepath.Join(root, "frontend/.bin/tailwindcss")
	if _, err := os.Stat(bin); err != nil {
		return "tailwindcss"
	}
	return bin
}

// tailwindCmd builds one CSS compile command.
func tailwindCmd(root, in, out string, watch bool) *exec.Cmd {
	args := []string{"--input", in, "--output", out}
	if watch {
		args = append(args, "--watch")
	} else {
		args = append(args, "--minify")
	}
	return exec.Command(tailwindBin(root), args...)
}

// buildCSS compiles the shared bundle and one bundle per style pack.
func buildCSS(root string) error {
	cmd := tailwindCmd(root, filepath.Join(root, "frontend/src/app.css"),
		filepath.Join(root, "assets/dist/app.css"), false)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("tailwind: %w (run `make tailwind-bin` to install the standalone binary)", err)
	}

	for _, style := range styles {
		entry, err := entryFor(root, style)
		if err != nil {
			return err
		}
		cmd := tailwindCmd(root, entry,
			filepath.Join(root, "assets/dist/style-"+style+".css"), false)
		cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
		err = cmd.Run()
		_ = os.Remove(entry)
		if err != nil {
			return fmt.Errorf("tailwind (%s): %w", style, err)
		}
	}
	return nil
}

// repoRoot walks up from the working directory to the module root (go.work).
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("run from inside the steward repository (go.work not found)")
		}
		dir = parent
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}
